USE Females
GO
ALTER DATABASE Females SET ALLOW_SNAPSHOT_ISOLATION ON

SET TRANSACTION ISOLATION LEVEL SNAPSHOT
BEGIN TRAN
SELECT * FROM Profesion WHERE Pid =2
WAITFOR DELAY '00:00:10'
UPDATE Profesion
SET PName = 'Researcher'
WHERE Pid = 2
COMMIT TRAN

select * from Female
SELECT * FROM Profesion
SELECT * FROM KnownFor